-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 19:26:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema security_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema security_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `security_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `security_db` ;

-- -----------------------------------------------------
-- Table `security_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`user` (
  `account_balance` DOUBLE NOT NULL,
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `confirm_password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `payment_code` VARCHAR(255) NULL DEFAULT NULL,
  `is_active` BIT(1) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UKob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`history_listing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`history_listing` (
  `history_listing_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`history_listing_id`),
  UNIQUE INDEX `UKjv57joq8h9o4n7gp7cstcnuiy` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKl32r2y5v4wmi42c91oopa9upi`
    FOREIGN KEY (`user_id`)
    REFERENCES `security_db`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`properties` (
  `history_list_id` INT NULL DEFAULT NULL,
  `property_bathrooms` INT NULL DEFAULT NULL,
  `property_bedrooms` INT NULL DEFAULT NULL,
  `property_floor` INT NULL DEFAULT NULL,
  `property_id` INT NOT NULL AUTO_INCREMENT,
  `property_is_available` BIT(1) NULL DEFAULT NULL,
  `property_price` DOUBLE NULL DEFAULT NULL,
  `property_square_meters` DOUBLE NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `property_description` LONGTEXT NULL DEFAULT NULL,
  `property_interior` VARCHAR(255) NULL DEFAULT NULL,
  `property_legal_papers` VARCHAR(255) NULL DEFAULT NULL,
  `property_status` VARCHAR(255) NULL DEFAULT NULL,
  `property_title` VARCHAR(255) NULL DEFAULT NULL,
  `property_type` VARCHAR(255) NULL DEFAULT NULL,
  `property_type_transaction` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`property_id`),
  INDEX `FK5dk0dlfrg0vh112mqvswe3cys` (`history_list_id` ASC) VISIBLE,
  INDEX `FKquwk7bgwa55ofxqufldn2vb2x` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK5dk0dlfrg0vh112mqvswe3cys`
    FOREIGN KEY (`history_list_id`)
    REFERENCES `security_db`.`history_listing` (`history_listing_id`),
  CONSTRAINT `FKquwk7bgwa55ofxqufldn2vb2x`
    FOREIGN KEY (`user_id`)
    REFERENCES `security_db`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `property_id` INT NULL DEFAULT NULL,
  `district` VARCHAR(255) NULL DEFAULT NULL,
  `full_address` VARCHAR(255) NULL DEFAULT NULL,
  `province` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `ward` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`address_id`),
  UNIQUE INDEX `UKfog6ojr29kwm7hkfbjg81wcny` (`property_id` ASC) VISIBLE,
  CONSTRAINT `FKp75ug6116ndsgdydiw4njlha5`
    FOREIGN KEY (`property_id`)
    REFERENCES `security_db`.`properties` (`property_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image_user_id` INT NULL DEFAULT NULL,
  `property_id` INT NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`image_id`),
  UNIQUE INDEX `UKdo4jl8ytewpmod6dlnkg0weg9` (`image_user_id` ASC) VISIBLE,
  INDEX `FK886uo2frx2ri49m81iuvhlm7a` (`property_id` ASC) VISIBLE,
  CONSTRAINT `FK13vy3a7v4nh87jt085di7g42h`
    FOREIGN KEY (`image_user_id`)
    REFERENCES `security_db`.`user` (`user_id`),
  CONSTRAINT `FK886uo2frx2ri49m81iuvhlm7a`
    FOREIGN KEY (`property_id`)
    REFERENCES `security_db`.`properties` (`property_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`payment` (
  `payment_amount` DOUBLE NULL DEFAULT NULL,
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `payment_property_id` INT NULL DEFAULT NULL,
  `payment_date` VARCHAR(255) NULL DEFAULT NULL,
  `payment_method` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE INDEX `UKc17hre16u7i1trwohek2k43oc` (`payment_property_id` ASC) VISIBLE,
  CONSTRAINT `FKi77q65fv69xnxf0l4dqosxdvv`
    FOREIGN KEY (`payment_property_id`)
    REFERENCES `security_db`.`properties` (`property_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`post_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`post_information` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `days_remaining` INT NOT NULL,
  `pay_per_day` DOUBLE NOT NULL,
  `payment` DOUBLE NOT NULL,
  `post_property_id` INT NULL DEFAULT NULL,
  `date_end` VARCHAR(255) NULL DEFAULT NULL,
  `date_post` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `type_post` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`contact_id`),
  UNIQUE INDEX `UKl1jsrk00jkxd7xaaak5enmpw` (`post_property_id` ASC) VISIBLE,
  CONSTRAINT `FKdju7tjmts5vdr99pbtti3in3u`
    FOREIGN KEY (`post_property_id`)
    REFERENCES `security_db`.`properties` (`property_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`rental_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`rental_history` (
  `price` DOUBLE NULL DEFAULT NULL,
  `properties_id` INT NULL DEFAULT NULL,
  `rental_history_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `created_at` VARCHAR(255) NULL DEFAULT NULL,
  `source` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`rental_history_id`),
  INDEX `FKj96ulxiw1p4hylhnhsxfosupy` (`properties_id` ASC) VISIBLE,
  INDEX `FKchic8sx425bch16wqaaeo23xn` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKchic8sx425bch16wqaaeo23xn`
    FOREIGN KEY (`user_id`)
    REFERENCES `security_db`.`user` (`user_id`),
  CONSTRAINT `FKj96ulxiw1p4hylhnhsxfosupy`
    FOREIGN KEY (`properties_id`)
    REFERENCES `security_db`.`properties` (`property_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`sales_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`sales_history` (
  `price` DOUBLE NULL DEFAULT NULL,
  `properties_id` INT NULL DEFAULT NULL,
  `sale_history_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `create_date` VARCHAR(255) NULL DEFAULT NULL,
  `source` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`sale_history_id`),
  INDEX `FKt3fya1y0cwcv15rbkg46bfnns` (`user_id` ASC) VISIBLE,
  INDEX `FKsy97m60sfn8m90kmj3q6nh8hn` (`properties_id` ASC) VISIBLE,
  CONSTRAINT `FKsy97m60sfn8m90kmj3q6nh8hn`
    FOREIGN KEY (`properties_id`)
    REFERENCES `security_db`.`properties` (`property_id`),
  CONSTRAINT `FKt3fya1y0cwcv15rbkg46bfnns`
    FOREIGN KEY (`user_id`)
    REFERENCES `security_db`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`user_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`user_payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE INDEX `UKrhd1vv34f2t1u6v9mh1xw6y69` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK8fb9fr82lb1qk2cw55ito9rk6`
    FOREIGN KEY (`user_id`)
    REFERENCES `security_db`.`user` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`user_payemnt_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`user_payemnt_details` (
  `payment_amount` DOUBLE NULL DEFAULT NULL,
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `payment_user_id` INT NULL DEFAULT NULL,
  `payment_date` VARCHAR(255) NULL DEFAULT NULL,
  `payment_method` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `FKqi798j7qfw1a9dx78r0e4t60n` (`payment_user_id` ASC) VISIBLE,
  CONSTRAINT `FKqi798j7qfw1a9dx78r0e4t60n`
    FOREIGN KEY (`payment_user_id`)
    REFERENCES `security_db`.`user_payment` (`payment_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `security_db`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `security_db`.`user_role` (
  `role_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `FKa68196081fvovjhkek5m97n3y` (`role_id` ASC) VISIBLE,
  INDEX `FK859n2jvi8ivhui0rl0esws6o` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK859n2jvi8ivhui0rl0esws6o`
    FOREIGN KEY (`user_id`)
    REFERENCES `security_db`.`user` (`user_id`),
  CONSTRAINT `FKa68196081fvovjhkek5m97n3y`
    FOREIGN KEY (`role_id`)
    REFERENCES `security_db`.`role` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
